### ISSUE TITLE
Portfolio: Works section is not displayed

### ISSUE THREAD

**Issue by OybekKayumov** [gtekle/Portfolio#13]
[projectss should be replaced by project](https://github.com/gtekle/Portfolio/blob/4b180e60c165a309138ca240fa4c92d673061fea/js/main.js#L95)

[projectss should be replaced by project](https://github.com/gtekle/Portfolio/blob/4b180e60c165a309138ca240fa4c92d673061fea/js/main.js#L97)

[projectss should be replaced by project](https://github.com/gtekle/Portfolio/blob/4b180e60c165a309138ca240fa4c92d673061fea/js/main.js#L104)

**Comment by gtekle** [comment]
Hello @OybekKayumov 
Thank you for the good catch and the issues are now resolved.

**Comment by gtekle** [comment]
Thank you for the good catch and the issues are now resolved.
