### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by rachidelaid** [gtekle/Portfolio#4]
- it would be better if the `.about-me` section had the styling of the 2 div wrappers, and remove those divs. that way your code will be cleaner.
- and I think the `.about-me` section should have 2 direct children. that way it will be easier to move to the desktop version.

**Comment by mrparkersson** [comment]
Okay please I would look into that and fix it. Thanks for your feedback @rachidelaid

**Comment by gtekle** [comment]
Thank you very much: @rachidelaid , @aimemalaika and @mrparkersson for your the good catches:
    1. Made the project card to contain image div and project detail div
    2. Removed the max-width CSS from container class
    3. Removed unnecessary used container class in HTML section/div tags
    4. Rearranged the layout of the header and the about-me sections
